### ISSUE TITLE
Razor Pay Payment Issue "So

### ISSUE THREAD

**Issue by creativetechify** [SOURABH2809/MediLink#1]
Pls, look into it and try helping me
![Screenshot (142)](https://github.com/user-attachments/assets/62abd33d-1be2-4218-9b13-8d8164b0b458)
![Screenshot (143)](https://github.com/user-attachments/assets/d2a04872-6d48-4853-8251-9d6b113d63be)

**Comment by SOURABH2809** [comment]
The Razorpay API key you are currently using is set for test mode only. To enable the full functionality of Razorpay, including live transactions, you'll need to create an account on Razorpay in live mode
